# Generated by Django 5.2 on 2025-06-02 17:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
        ('viajes', '0003_alter_viaje_options_viaje_cancelled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-fecha_reserva']},
        ),
        migrations.AddField(
            model_name='reserva',
            name='importe',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Importe que debe pagar el viajero', max_digits=8),
        ),
        migrations.AddField(
            model_name='reserva',
            name='pagado',
            field=models.BooleanField(default=False, help_text='True cuando el viajero haya pagado'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(fields=('viaje', 'viajero'), name='unique_reserva_por_usuario_y_viaje'),
        ),
    ]
