# Generated by Django 5.2 on 2025-05-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
