# Generated by Django 5.2 on 2025-05-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viaje',
            options={'ordering': ['-fecha_inicio']},
        ),
        migrations.AddField(
            model_name='viaje',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Foto representativa de la ruta', null=True, upload_to='viajes/'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='plazas_disponibles',
            field=models.PositiveIntegerField(default=0, help_text='Número de plazas aún disponibles'),
        ),
    ]
