# Generated by Django 5.2 on 2025-05-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0002_alter_viaje_options_viaje_imagen_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viaje',
            options={},
        ),
        migrations.AddField(
            model_name='viaje',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='viajes/'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='plazas_disponibles',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
