# Generated by Django 5.2 on 2025-04-29 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal')], max_length=10)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(choices=[('pagado', 'Pagado'), ('pendiente', 'Pendiente'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=12)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='reservas.reserva')),
            ],
        ),
    ]
